# Generated by Django 4.0.1 on 2022-01-13 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('NT', 'Natural'), ('TG', 'Technogenic'), ('AG', 'Anthropogenic'), ('EC', 'Ecological')], max_length=150)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('radius', models.IntegerField(default=0)),
                ('description', models.TextField(default=' ')),
                ('is_showing', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
