# Generated by Django 4.0.1 on 2022-01-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='name',
            field=models.CharField(default='Default name', max_length=150),
        ),
    ]
